include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    use_build_context_synchronously: false
    cast_nullable_to_non_nullable: false
    sized_box_for_whitespace: false
    prefer_const_constructors_in_immutables: false
    sort_pub_dependencies: false
    implicit_dynamic_parameter: false
    implicit_dynamic_map_literal: false
