name: ez_parking_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Manejo de estados  
  flutter_bloc: ^7.1.0
  intl: ^0.17.0
  # Sirve para comparar varias instancias de un objeto
  equatable: ^2.0.3
  # Sirve para hacer peticiones http a un servidor
  http: ^0.13.3
  # Sirve para utilizar el objeto Either
  dartz: ^0.10.0-nullsafety.2
  # Sirve para comprobar la conexion a internet del dispositivo
  internet_connection_checker: ^0.0.1+1
  # Liberia de google fonts
  google_fonts: ^2.1.0
  # Getit
  get_it: ^7.2.0
  # Libreria para ver si el teclado se encuentra activado
  flutter_keyboard_visibility: ^5.0.2
  # Libreria para guardar informacion en el secure storage del dispositivo
  flutter_secure_storage: ^4.2.0
  # Libreria para enviar eventos por medio de sockets
  event_bus: ^2.0.0
  # Libreria para tomar screenshots de widgets
  screenshot: ^1.2.3
  # Libreria para descargar imagen a galeria
  image_gallery_saver: '^1.6.9'
  # Libreria para solicitar permisos al app
  permission_handler: ^8.1.4+2
  # Libreria para OnBoarding
  flutter_onboarding_slider: ^1.0.0
  # Libreria de shared preferences
  shared_preferences: ^2.0.6
  # Libreria para UI de tarjeta de credito
  awesome_card: ^1.1.5
  # Libreria para renderizar archivos svg
  flutter_svg: ^0.22.0
  # Libreria para formatear inputs
  flutter_multi_formatter: ^2.3.3
  # Libreria para mostrar alertas nativas
  adaptive_dialog: ^1.1.0
  # Pull to refresh
  pull_to_refresh: ^2.0.0
  # Libreria para NFC
  nfc_manager: ^3.1.0
  # Libreria para tutorial overlay
  tutorial: ^1.0.8

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0
  # Libreria para iconos de android
  flutter_launcher_icons: "^0.9.2"
  # Libreria para splashscreen
  flutter_native_splash: ^1.2.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/company_logo.png"

flutter_native_splash:
  color: "#ffffff"
  # The image parameter allows you to specify an image used in the splash screen.  It must be a 
  # png file and should be sized for 4x pixel density.
  image: assets/images/company_logo.png
  web: false
  android_gravity: center
  ios_content_mode: center

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
